# Employee Attrition Prediction & HR Analytics Platform

## Day 2 - Dataset Understanding

In [2]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

In [3]:
DATA_PATH = "/content/drive/MyDrive/EmployeeAttrition/Employee_Dataset.csv"

In [4]:
import os
print(os.path.exists(DATA_PATH))

True

In [5]:
import pandas as pd

data = pd.read_csv(DATA_PATH)

In [6]:
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [7]:
data.shape

(1470, 35)

In [8]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [9]:
data.info

<bound method DataFrame.info of       Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales
1      49        No  Travel_Frequently        279  Research & Development
2      37       Yes      Travel_Rarely       1373  Research & Development
3      33        No  Travel_Frequently       1392  Research & Development
4      27        No      Travel_Rarely        591  Research & Development
...   ...       ...                ...        ...                     ...
1465   36        No  Travel_Frequently        884  Research & Development
1466   39        No      Travel_Rarely        613  Research & Development
1467   27        No      Travel_Rarely        155  Research & Development
1468   49        No  Travel_Frequently       1023                   Sales
1469   34        No      Travel_Rarely        628  Research & Development

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1
1                    8          1  Life Sciences              1
2                    2          2          Other              1
3                    3          4  Life Sciences              1
4                    2          1        Medical              1
...                ...        ...            ...            ...
1465                23          2        Medical              1
1466                 6          1        Medical              1
1467                 4          3  Life Sciences              1
1468                 2          3        Medical              1
1469                 8          3        Medical              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80
1                  2  ...                         4            80
2                  4  ...                         2            80
3                  5  ...                         3            80
4                  7  ...                         4            80
...              ...  ...                       ...           ...
1465            2061  ...                         3            80
1466            2062  ...                         1            80
1467            2064  ...                         2            80
1468            2065  ...                         4            80
1469            2068  ...                         1            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0
1                    1                 10                      3
2                    0                  7                      3
3                    0                  8                      3
4                    1                  6                      3
...                ...                ...                    ...
1465                 1                 17                      3
1466                 1                  9                      5
1467                 1                  6                      0
1468                 0                 17                      3
1469                 0                  6                      3

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4
1                  3              10                  7
2                  3               0                  0
3                  3               8                  7
4                  3               2                  2
...              ...             ...                ...
1465               3               5                  2
1466               3               7                  7
1467               3               6                  2
1468               2               9                  6
1469               4               4                  3

      YearsSinceLastPromotion  YearsWithCurrManager
0                           0                     5
1                           1                     7
2                           0                     0
3                           3                     0
4                           2                     2
...                       ...                   ...
1465                        0                     3
1466                        1                     7
1467                        0                     3
1468                        0                     8
1469                        1                     2

[1470 rows x 35 columns]>

In [10]:
data.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [11]:
data.duplicated().sum()

np.int64(0)

In [12]:
data["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [13]:
data["Attrition"].value_counts(normalize=True)*100

Attrition
No     83.877551
Yes    16.122449
Name: proportion, dtype: float64

In [14]:
data_dictionary = pd.DataFrame({
    "Column": data.columns,
    "Data Type": data.dtypes.astype(str).values,
    "Unique Values": [data[col].nunique() for col in data.columns],
    "Missing Values": [data[col].isnull().sum() for col in data.columns]
})

data_dictionary

                      Column Data Type  Unique Values  Missing Values
0                        Age     int64             43               0
1                  Attrition    object              2               0
2             BusinessTravel    object              3               0
3                  DailyRate     int64            886               0
4                 Department    object              3               0
5           DistanceFromHome     int64             29               0
6                  Education     int64              5               0
7             EducationField    object              6               0
8              EmployeeCount     int64              1               0
9             EmployeeNumber     int64           1470               0
10   EnvironmentSatisfaction     int64              4               0
11                    Gender    object              2               0
12                HourlyRate     int64             71               0
13            JobInvolvement     int64              4               0
14                  JobLevel     int64              5               0
15                   JobRole    object              9               0
16           JobSatisfaction     int64              4               0
17             MaritalStatus    object              3               0
18             MonthlyIncome     int64           1349               0
19               MonthlyRate     int64           1427               0
20        NumCompaniesWorked     int64             10               0
21                    Over18    object              1               0
22                  OverTime    object              2               0
23         PercentSalaryHike     int64             15               0
24         PerformanceRating     int64              2               0
25  RelationshipSatisfaction     int64              4               0
26             StandardHours     int64              1               0
27          StockOptionLevel     int64              4               0
28         TotalWorkingYears     int64             40               0
29     TrainingTimesLastYear     int64              7               0
30           WorkLifeBalance     int64              4               0
31            YearsAtCompany     int64             37               0
32        YearsInCurrentRole     int64             19               0
33   YearsSinceLastPromotion     int64             16               0
34      YearsWithCurrManager     int64             18               0

In [15]:
numericals_columns=data.select_dtypes(include=['int64','float64']).columns

numericals_columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [16]:
categorical_columns=data.select_dtypes(include='object').columns

categorical_columns

Index(['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender',
       'JobRole', 'MaritalStatus', 'Over18', 'OverTime'],
      dtype='object')

In [17]:
constant_columns = []

for col in data.columns:
    unique_values = data[col].nunique()

    if unique_values == 1:
        constant_columns.append(col)

print(constant_columns)

['EmployeeCount', 'Over18', 'StandardHours']

In [19]:
data["EmployeeNumber"].nunique()

1470

In [20]:
data.shape[0]

1470

In [21]:
data.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [22]:
data["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [23]:
data["JobRole"].value_counts()

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

In [24]:
data["OverTime"].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [25]:
data["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [26]:
data_dictionary = pd.DataFrame({
    "Column": data.columns,
    "Data Type": data.dtypes.astype(str).values,
    "Unique Values": [data[col].nunique() for col in data.columns],
    "Missing Values": [data[col].isnull().sum() for col in data.columns]
})

data_dictionary

                      Column Data Type  Unique Values  Missing Values
0                        Age     int64             43               0
1                  Attrition    object              2               0
2             BusinessTravel    object              3               0
3                  DailyRate     int64            886               0
4                 Department    object              3               0
5           DistanceFromHome     int64             29               0
6                  Education     int64              5               0
7             EducationField    object              6               0
8              EmployeeCount     int64              1               0
9             EmployeeNumber     int64           1470               0
10   EnvironmentSatisfaction     int64              4               0
11                    Gender    object              2               0
12                HourlyRate     int64             71               0
13            JobInvolvement     int64              4               0
14                  JobLevel     int64              5               0
15                   JobRole    object              9               0
16           JobSatisfaction     int64              4               0
17             MaritalStatus    object              3               0
18             MonthlyIncome     int64           1349               0
19               MonthlyRate     int64           1427               0
20        NumCompaniesWorked     int64             10               0
21                    Over18    object              1               0
22                  OverTime    object              2               0
23         PercentSalaryHike     int64             15               0
24         PerformanceRating     int64              2               0
25  RelationshipSatisfaction     int64              4               0
26             StandardHours     int64              1               0
27          StockOptionLevel     int64              4               0
28         TotalWorkingYears     int64             40               0
29     TrainingTimesLastYear     int64              7               0
30           WorkLifeBalance     int64              4               0
31            YearsAtCompany     int64             37               0
32        YearsInCurrentRole     int64             19               0
33   YearsSinceLastPromotion     int64             16               0
34      YearsWithCurrManager     int64             18               0

In [34]:
import os

os.makedirs("/content/reports", exist_ok=True)

In [35]:
data_dictionary.to_csv(
    "/content/reports/data_dictionary.csv",
    index=False
)

In [36]:
os.listdir("/content/reports")

['data_dictionary.csv']